add check to verify that number of txt files of builds matches the actual number of snaps

diff --git a/.github/workflows/monthly-builds.yaml b/.github/workflows/monthly-builds.yaml
--- a/.github/workflows/monthly-builds.yaml
+++ b/.github/workflows/monthly-builds.yaml
@@ -74,6 +74,14 @@ jobs:
         with:
           path: /home/runner/work/ros-content-sharing-snaps/ros-content-sharing-snaps/${{ matrix.snap_names }}
           snapcraft-args: "remote-build --launchpad-accept-public-upload --build-id ${{ matrix.snap_names }}-${SNAPCRAFT_BUILDER_ID}"
+      - name: check number of built snaps
+        run: |
+          count_txt_files=$(find /home/runner/work/ros-content-sharing-snaps/ros-content-sharing-snaps/${{ matrix.snap_names }} -type f -name 'ros-*.txt' | wc -l)
+          count_snap_files=$(find ${{ matrix.snap_names }} -type f -name '*.snap' | wc -l)
+          if [ "$count_txt_files" -ne "$count_snap_files" ]; then
+            echo "Error: The number of '.txt' files and '.snap' files do not match."
+            exit 1
+          fi
       - uses: actions/upload-artifact@v3
         name: Upload snapcraft logs
         if: always()
